### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by yikedouer** [donghyeonk/fastText1607#1]
Hi, the link of data doesn't work,I cannot download it. Could you help me?

**Comment by donghyeonk** [comment]
Hi, I modified the link address. (https://www.di.unipi.it/~gulli/newsSpace.bz2)

More information can be found at http://www.di.unipi.it/~gulli/AG_corpus_of_news_articles.html

**Comment by yikedouer** [comment]
Thanks very much, that helps me a lot.
