### ISSUE TITLE
Input dataset

### ISSUE THREAD

**Issue by BinWang28** [donghyeonk/fastText1607#2]
Thanks so much for sharing your code.

I have one question about the input dataset.
If we want to test on other dataset in the provided drive link.
Can we simply change the input path? I can see there is a AGData class in dataset.py. It is only designed for AG dataset or we can also use this class for other dataset like yelp.

Thanks so much in advance.

**Comment by donghyeonk** [comment]
Thank you for your interest.

The AGData class only preprocesses AG's corpus of news articles and requires additional coding for Yelp data.

After making a pickle file for Yelp data, you can set the input path as follows:
python3 main.py --data_path=<yelp_pickle_path>

**Comment by BinWang28** [comment]
Thanks so much! Will check!
