### ISSUE TITLE
I want to ask you a question about this experiment

### ISSUE THREAD

**Issue by Ellie24678** [donghyeonk/fastText1607#3]
Hello,Nice to meet you, I am running your experiment, there is an error in the file ag.pkl.May I ask if you wrote this document by yourself?Is this an empty file?
Could you please reply to me sometime? Thank you very much!

**Comment by Ellie24678** [comment]
Hello,Nice to meet you, I am running your experiment, there is an error in the file ag.pkl.May I ask if you wrote this document by yourself?Is this an empty file?
Could you please reply to me sometime? Thank you very much!

**Comment by donghyeonk** [comment]
Nice to meet you, @Ellie24678 .

Thank you for your interest.

Follow these steps one by one.

1. Download ag_news_csv.tar.gz file from Xiang Zhang's folder (https://drive.google.com/drive/u/0/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M).

2. Make "data" directory in the project home.
mkdir data

3. Extract train.csv and test.csv to the "data" directory.

4. Download spacy en_core_web_lg model.
python3 -m spacy download en_core_web_lg --user

5. Create a pickle file (data/ag.pkl).
python3 dataset.py

6. Run
python3 main.py

Have a nice day :)

**Comment by Ellie24678** [comment]
Thank you very much!
