### ISSUE TITLE
Please help me solve the problem again

### ISSUE THREAD

**Issue by Ellie24678** [donghyeonk/fastText1607#4]
Hello:
  When I ran this experiment according to the steps you gave me last time, there was still a problem. I would like to ask if there is anything in the pkl file, is it an empty file?If it is an empty file, I run it with an error: Ran out of input.Thank you very much for answering my question!

Have a nice day!

**Comment by donghyeonk** [comment]
Hi Ellie,

Sorry for late reply.

The pkl file is not an empty file.

I uploaded ag.pkl file for you at http://gofile.me/6pN25/zE8RZrW9D

If you have any problem, let me know the problem.

Have a great day.

**Comment by Ellie24678** [comment]
Hi donghyeonk：
Thank you very much!

Have a good day!
